### ISSUE TITLE
Have a way to force cron to be used instead of systemd

### ISSUE THREAD

**Issue by jstaf** [roles-ansible/ansible_role_restic#22]
There should also be a way to force cronjobs only instead of a systemd timer (for various reasons, it may be preferable to use cron instead of systemd). Right now I can set `restic_force_cron: true` to ensure a cronjob is created and then purge the resulting the duplicate systemd timers via an extra task in my playbooks:

```
- name: Disable duplicate restic timers if present
  systemd:
    name: "restic-{{ item.name }}.timer"
    state: stopped
    enabled: no
  loop: "{{ restic_backups }}"
```

I would like to use this role to backup stuff via restic, while ensuring cron gets used to provision the backups instead of systemd timers.
