### ISSUE TITLE
Fails with Ansible 5

### ISSUE THREAD

**Issue by rxbn** [roles-ansible/ansible_role_restic#49]
First of all: Thanks a lot for creating this awesome role!

Unfortunately it doesn't work for me. As far as I can tell, ansible deprecated the use of /etc/crontab for managing cronjob.

Here are my vars:
```yaml
restic_create_schedule: true
restic_schedule_type: systemd
restic_repos:
  minio:
    location: s3:https://example.com/example
    password: "{{ restic_password }}"
    init: true
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_access_key: "{{ aws_secret_access_key }}"
restic_backups:
  example:
    name: example-db
    repo: minio
    stdin: true
    stdin_cmd: docker exec example-postgres pg_dumpall -U postgres
    stdin_filename: postgres_dump.sql
    scheduled: true
    schedule_oncalendar: '*-*-* 01:00:00'
```

When running the playbook it wants to cleanup old crontab entries which fails, since it cannot change /etc/crontab files anymore.

Log:
```text
TASK [do1jlr.restic : delete old cronjob entry if available] ***********************************************************************************************************************************************
failed: [] (item={'name': 'example-db', 'repo': 'minio', 'stdin': True, 'stdin_cmd': 'docker exec example-postgres pg_dumpall -U postgres', 'stdin_filename': 'postgres_dump.sql', 'scheduled': True, 'schedule_oncalendar': '*-*-* 01:00:00'}) => {"ansible_loop_var": "item", "changed": false, "item": {"name": "example-db", "repo": "minio", "schedule_oncalendar": "*-*-* 01:00:00", "scheduled": true, "stdin": true, "stdin_cmd": "docker exec example-postgres pg_dumpall -U postgres", "stdin_filename": "postgres_dump.sql"}, "msg": "Will not manage /etc/crontab via cron_file, see documentation."}
```

Since it "failed" to create a systemd timer, the role then wants to create a cronjob, which also fails for the same reason.

I think you have to remove or change the `cron_file` value [here](https://github.com/roles-ansible/ansible_role_restic/blob/e614bdc66180692ee29906502514ba6349675949/tasks/schedule.yml#L83).

Thanks for having a look at it!
